{{- if .Values.useNamespaceResource }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{ include "backyards-demo.labels" . | nindent 4 }}
    istio-injection: enabled
{{- end }}
