{{- if .Values.als.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "als.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "als.name" . }}
    app.kubernetes.io/name: {{ include "als.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: als
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "als.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "als.name" . }}
    app.kubernetes.io/name: {{ include "als.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: als
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "als.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "als.name" . }}
    app.kubernetes.io/name: {{ include "als.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: als
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
roleRef:
  kind: Role
  name: {{ include "als.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "als.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
