apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: mesh
spec:
  version: "1.5.0"
  mtls: false
  autoMtls: true
  meshExpansion: true
  controlPlaneSecurityEnabled: true
  sidecarInjector:
    enabled: false
    rewriteAppHTTPProbe: true
    injectedContainerAdditionalEnvVars:
    - name: ISTIO_METAJSON_PLATFORM_METADATA
      value: |
        {"PLATFORM_METADATA":{"cluster_id":"master"}}
  imagePullPolicy: Always
  citadel:
    enabled: false
  galley:
    enabled: false
  gateways:
    ingress:
      maxReplicas: 1
      ports:
      - name: status-port
        port: 15020
        protocol: TCP
        targetPort: 15020
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
      - name: tls
        port: 15443
        protocol: TCP
        targetPort: 15443
      - name: tcp-als-tls
        port: 50600
        protocol: TCP
        targetPort: 50600
      - name: tcp-zipkin-tls
        port: 59411
        protocol: TCP
        targetPort: 59411
    egress:
      enabled: false
  pilot:
    enabled: false
    maxReplicas: 1
    image: banzaicloud/istio-pilot:1.5.0-bzc
  proxy:
    image: banzaicloud/istio-proxyv2:1.5.0-bzc.0
    useMetadataExchangeFilter: true
    envoyAccessLogService:
      enabled: true
      host: backyards-als.backyards-system.svc.cluster.local
      port: 50600
      tcpKeepalive:
        interval: 10s
        probes: 3
        time: 10s
      tlsSettings:
        mode: ISTIO_MUTUAL
  mixer:
    maxReplicas: 1
    image: banzaicloud/istio-mixer:1.5.0-bzc
    multiClusterSupport: true
  telemetry:
    enabled: false
    maxReplicas: 1
  policy:
    enabled: false
    maxReplicas: 1
  tracing:
    enabled: true
    tracer: zipkin
    zipkin:
      address: backyards-zipkin.backyards-system.svc.cluster.local:59411
      tlsSettings:
        mode: ISTIO_MUTUAL
  istiod:
    enabled: true
  jwtPolicy: first-party-jwt
  mixerlessTelemetry:
    enabled: true
