apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: mesh
spec:
  version: "1.4.3"
  mtls: false
  autoMtls: true
  meshExpansion: true
  controlPlaneSecurityEnabled: true
  sidecarInjector:
    rewriteAppHTTPProbe: true
  imagePullPolicy: Always
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      enabled: false
  pilot:
    image: banzaicloud/istio-pilot:1.4.2-bzc
  proxy:
    useMetadataExchangeFilter: true
    envoyAccessLogService:
      enabled: true
      host: backyards-als.backyards-system.svc.cluster.local
      port: 8080
      tcpKeepalive:
        interval: 10s
        probes: 3
        time: 10s
      tlsSettings:
        mode: DISABLE
  mixer:
    image: banzaicloud/istio-mixer:1.4.2-bzc
    multiClusterSupport: true
  tracing:
    enabled: true
    tracer: zipkin
    zipkin:
      address: backyards-zipkin.backyards-system:9411
