apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: mesh
spec:
  version: "1.4.0"
  mtls: true
  autoMtls: false
  controlPlaneSecurityEnabled: true
  sidecarInjector:
    rewriteAppHTTPProbe: true
  imagePullPolicy: Always
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      enabled: false
  pilot:
    image: banzaicloud/istio-pilot:1.4.0-bzc
  mixer:
    image: banzaicloud/istio-mixer:1.4.0-bzc
  tracing:
    enabled: true
    tracer: zipkin
    zipkin:
      address: backyards-zipkin.backyards-system:9411
