apiVersion: v1
description: Backyards manages hybrid clusters connected with Istio
name: backyards
version: 0.1.6

appVersion: 0.1.3

home: https://banzaicloud.com

maintainers:
  - name: Banzai Cloud
    email: info@banzaicloud.com

sources:
  - https://github.com/banzaicloud/backyards

icon: https://banzaicloud.com/img/banzai-cloud-logo.png
