apiVersion: v1
kind: Service
metadata:
  labels:
    app: backyards-als
    app.kubernetes.io/component: als
    app.kubernetes.io/instance: backyards
    app.kubernetes.io/name: backyards-als
    app.kubernetes.io/part-of: backyards
  name: backyards-als
  namespace: backyards-system
spec:
  externalName: istio-pilot.istio-system.svc.cluster.local
  type: ExternalName
