apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: backyards
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: backyards
  name: backyards-zipkin
  namespace: backyards-system
spec:
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
  type: ClusterIP
