apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-operator
subjects:
- kind: ServiceAccount
  name: istio-operator
  namespace: {{ .Release.Namespace }}
