# Default values for backyards-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2

image:
  repository: banzaicloud/allspark
  tag: "0.1.1"
  pullPolicy: IfNotPresent

resources: {}
  # limits:
  #  cpu: 200m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 64Mi

services: true

istioresources: true

bombardier: true
analytics: true
bookings: true
catalog: true
frontpage: true
moviesv1: true
moviesv2: true
moviesv3: true
notifications: true
payments: true
database: true
